# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_hyper_process <- function(telemetry) {
    .Call(`_RHyper_create_hyper_process`, telemetry)
}

create_hyper_connection <- function(process_ptr, database) {
    .Call(`_RHyper_create_hyper_connection`, process_ptr, database)
}

disconnect <- function(connection_ptr) {
    invisible(.Call(`_RHyper_disconnect`, connection_ptr))
}

is_ready <- function(connection_ptr) {
    .Call(`_RHyper_is_ready`, connection_ptr)
}

terminate <- function(process_ptr) {
    invisible(.Call(`_RHyper_terminate`, process_ptr))
}

attach_database <- function(connection_ptr, db_file) {
    invisible(.Call(`_RHyper_attach_database`, connection_ptr, db_file))
}

detach_database <- function(connection_ptr, db_name) {
    invisible(.Call(`_RHyper_detach_database`, connection_ptr, db_name))
}

query_execute <- function(conn, statement) {
    invisible(.Call(`_RHyper_query_execute`, conn, statement))
}

fetch_all <- function(res_) {
    .Call(`_RHyper_fetch_all`, res_)
}

fetch_n2 <- function(res_, iter_, iter_end_, n_) {
    .Call(`_RHyper_fetch_n2`, res_, iter_, iter_end_, n_)
}

create_result <- function(conn_, statement_) {
    .Call(`_RHyper_create_result`, conn_, statement_)
}

create_result_iterator <- function(res_) {
    .Call(`_RHyper_create_result_iterator`, res_)
}

clear_result <- function(res_) {
    invisible(.Call(`_RHyper_clear_result`, res_))
}

has_completed <- function(res_) {
    .Call(`_RHyper_has_completed`, res_)
}

hyper_quote_string <- function(x) {
    .Call(`_RHyper_hyper_quote_string`, x)
}

list_tables <- function(conn) {
    .Call(`_RHyper_list_tables`, conn)
}

is_null_pointer <- function(conn) {
    .Call(`_RHyper_is_null_pointer`, conn)
}

